language: python

script:
  - python setup.py sdist

deploy:
  provider: pypi
  user: gmarull
  password:
    secure: 45NtJr56shHRiwcOJoUI7pKDf1HVzSEqItmpfsYf7lplZLyJ+5NMox5Sb6SA0KWUoShI1TNWyRl8VfLiwayEN4AxmwT6e8a2XYX1DPwMAjsnVb8yD9PY4wTeIpizC5sO1KB9LadmM8fX/j9Ovy07lAs/yfcWYVMfMyDZL5Z3jqqsJbASMXfyUsD+mzPjtPagAX9jq0WFs66AfDenob0ZIqcL9SOVNHytFvpwzzbvUh+WBRucjgHjqpoPWFWjKKMDQ58q4O5A9cTLd3kzZuBBzbj4ZDBxZouMfWO44B6aFw6OnBvuTpqpZ7ro6jvRZwYdWPRs8lLy3lkuW+e71VIF1SbwJw8GDYF99A5U3FqYN4JmN8bV/3DVbVOYvIteThanCx2GNdJMaaxWfAah9kQV8A7mF177niF0t/odgvHImHxXxhJdATMPzj3ZUJle/V+sRoRciK55Vman29xPYrzZnSIyWGSVEInSuZ05mao9OtAqk+nyelVORBd6g8fhqj1+GxPD7w3dlSMPKS/uTfaBlnEjQD8EpC/GTJ7BrGPZsixqgYGtjyiTZFpMRxbFUsawxxfKlrBFz96kOs0ZpaWBKGJym5lBltsBOoM8UjhFbcFuHCSjYPPcOlMI7HnHESNH5H1iKZKbRzlZ+wMmagdwiXQBqbh+LNEgEGoN7/Ou1x0=
  on:
    branch: master
